<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "clean_blog"
 *
 * Auto generated by Extension Builder 2017-03-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Clean Blog',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Michael Blunck',
	'author_email' => 'mi.blunck@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'blog' => '1.2.0',
			'formhandler' => '2.3.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);